### ISSUE TITLE
Simplify plugin config for CI builds

### ISSUE THREAD

**Issue by michaelborn** [elpete/commandbox-semantic-release#12]
Check out the recommended config for the [Ortus Semantic Release Action](https://github.com/Ortus-Solutions/semantic-release-action):

```yaml
steps:
      - uses: actions/checkout@v2
      - uses: Ortus-Solutions/semantic-release-action@v1
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
          forgeboxToken: ${{ secrets.FORGEBOX_TOKEN }}
          excludeCommit: ${{ github.event.head_commit.message }}
          branch: main
          plugins: '{ "VerifyConditions": "GitHubActionsConditionsVerifier@commandbox-semantic-release", "FetchLastRelease": "ForgeBoxReleaseFetcher@commandbox-semantic-release", "RetrieveCommits": "JGitCommitsRetriever@commandbox-semantic-release", "ParseCommit": "EmojiLogCommitParser@commandbox-semantic-release", "FilterCommits": "DefaultCommitFilterer@commandbox-semantic-release", "AnalyzeCommits": "DefaultCommitAnalyzer@commandbox-semantic-release", "VerifyRelease": "NullReleaseVerifier@commandbox-semantic-release", "GenerateNotes": "GitHubMarkdownNotesGenerator@commandbox-semantic-release", "UpdateChangelog": "FileAppendChangelogUpdater@commandbox-semantic-release", "CommitArtifacts": "GitHubArtifactsCommitter@commandbox-semantic-release", "PublishRelease": "ForgeBoxReleasePublisher@commandbox-semantic-release", "PublicizeRelease": "GitHubReleasePublicizer@commandbox-semantic-release" }'
```

The `plugins` config is a nightmare, IMHO, and is very difficult to remember or use without simply pulling up an older project and copy/pasting the JSON block. 

How can we achieve the following?

```yaml
steps:
      - uses: actions/checkout@v2
      - uses: Ortus-Solutions/semantic-release-action@v1
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
          forgeboxToken: ${{ secrets.FORGEBOX_TOKEN }}
          excludeCommit: ${{ github.event.head_commit.message }}
          branch: main
          plugins.parseCommit: EmojiLogCommitParser@commandbox-semantic-release
          plugins.analyzeCommits: EmojiLogCommitAnalyzer@commandbox-semantic-release
```
